Icon
migcontrol/django-migcontrol pull request #51
Opened 2022-02-24 22:23 UTC by tchiliali

this is for icon

2022-02-24 22:28 UTC, benjaoming requested changes
As mentioned in the former review, please remove this

2022-02-24 22:28 UTC, benjaoming commented on migcontrol/templates/base.html
> +          <button class="fa fa-search" style="color:red" type="submit" >{% trans "" %}</button>
```suggestion
          <button class="fa fa-search" style="color:red" type="submit" ></button>
```

2022-02-27 11:43 UTC, tchiliali commented on migcontrol/templates/base.html
> +          <button class="fa fa-search" style="color:red" type="submit" >{% trans "" %}</button>
This will only affect line 110 right?

2022-02-27 14:59 UTC, benjaoming requested changes

2022-02-27 14:59 UTC, benjaoming commented on migcontrol/templates/base.html
> +          <button class="fa fa-search" style="color:red" type="submit" ></button>
Hi Tchili, you have added `style="color:red"` which is an inline style. We cannot and should not use this. Can you remove it? Thanks.

2022-03-09 19:22 UTC, merged